name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Install your ETL package in editable mode
      - name: Install ETL package
        run: |
          pip install -e .

      # 5️⃣ Run tests with PYTHONPATH pointing to project root
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
          pytest --maxfail=1 --disable-warnings -q

      

